apiVersion: v1
kind: Service
metadata:
  name: zookeeper-ip-service
spec:
  type: LoadBalancer 
  selector:
    component: zookeeper
  ports:
  - name: zookeeper
    port: 2181
    targetPort: 2181


  
